name: ci

on:
  schedule: [{ cron:  '0 3 * * *'}] # daily, at 3am

jobs:
  ci:
    strategy:
      matrix:
        os:   [ubunti, windows]
        node: [13, 12, 10]
        mongo: [4, 3]
        redis: [5, 4]
    steps:
      - { name: checkout                    , uses: actions/checkout@v2 }
      - name: node v${{ matrix.node }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: mongo start
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongo }}
      - name: redis start
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis }}
      - { name: env-info                    , run: 'npx envinfo' }
      - { name: install                     , run: 'npm i' }
      - { name: test                        , run: 'npm test' }
      - { name: cover                       , run: 'npm run cover' }
      - { name: archive                     , run: 'tar -czvf ci-results.tar.gz coverage' }
      - name: save
        uses: actions/upload-artifact@v1
        with:
          name: ci-results.os-${{ matrix.os }}.node-${{ matrix.node }}.mongo-${{ matrix.mongo }}.redis-${{ matrix.redis }}
          path: ci-results.tar.gz
